# Generated by Django 4.2 on 2023-04-22 20:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="fist_name",
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.EmailField(max_length=50),
        ),
    ]
