# Generated by Django 4.2 on 2023-04-25 18:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies_orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movieorder",
            name="buyed_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 4, 25, 18, 57, 2, 283212, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
