# Generated by Django 4.2 on 2023-04-25 19:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies_orders", "0002_alter_movieorder_buyed_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movieorder",
            name="buyed_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
