# Generated by Django 4.2 on 2023-04-25 19:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("movies", "0003_movie_orders"),
        ("movies_orders", "0003_alter_movieorder_buyed_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movieorder",
            name="movie",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="movies_orders",
                to="movies.movie",
            ),
        ),
        migrations.AlterField(
            model_name="movieorder",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_movies_orders",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
