# Generated by Django 4.2 on 2023-04-25 15:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("movies_orders", "0001_initial"),
        ("movies", "0002_alter_movie_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="orders",
            field=models.ManyToManyField(
                related_name="ordered_movies",
                through="movies_orders.MovieOrder",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
